新增加签函数，修改消息通知内容为卡片。
ayunwSky/promalert-feishu-webhook pull request #4
Opened 2023-03-21 05:34 UTC by 26cm

新增了gen_sign功能，消息通知从text改成了card；遗留：预期将“结束时间: 0001-01-01 08:05:43”进行区分，根据status是否firing，如果是firing则显示持续时间remain_time,但还没想好怎么写，时间计算有点复杂不会，否则显示结束时间。

2023-03-21 14:04 UTC, ayunwSky requested changes
谢谢您的PR，我很欣赏您将告警内容修改成卡片的形式，我想我们后续是否可以再添加一个变量来让用户自己选择需要将msg_type设置为 post 模式还是 interactive 模式，而不是直接否定掉了 post 模式。

另外，我已经将 gen_sign 加签单独到了一个utils工具类的目录下，还麻烦您这边更新一下。

2023-03-22 00:51 UTC, closed without merging

2023-03-22 02:40 UTC, ayunwSky commented
期待您的消息卡片类型代码再次提交

2023-03-22 06:07 UTC, 26cm commented
有注意到你的回复，我在琢磨，能否换一种实现:在alert message里面labels.messagetype来指定post card或者其他的一些消息类型，依据此来完善消息类型的选择。想法有，但是现在个人能力还达不到 ；-（ 属于边学边弄
&nbsp;


Zhu
***@***.***



&nbsp;

2023-03-22 06:20 UTC, 26cm commented
或许我们可以将一个/sendcard的接口用于发送interactive类型的消息，将/sendpost接口用于发送post类型的消息，但重复写一个接口感觉会太过累赘，实际不同的地方只是send_data这一块，如果你这边有更好的解决方式，期待你的回复。（我是python新手
&nbsp;


Zhu
***@***.***



&nbsp;

2023-03-22 09:47 UTC, ayunwSky commented
这样是一个好想法，我也同样认为拆分为两个接口是一个好方法。
上一次把您的PR驳回了，但是实际上您写的挺不错的。您现在可以就卡片消息重新发起PR。

2023-03-24 01:32 UTC, 26cm commented
重新发起了PR，新增了卡片消息和二次替换tags的语句。
&nbsp;


Zhu
***@***.***



&nbsp;